### ISSUE TITLE
Talas stuck inside table

### ISSUE THREAD

**Issue by IttyBittyNiko** [xavier150/MMVS#10] opened 2022-02-23 06:58 UTC
![MacroMicroVRService-Win64-Shipping_Wowxamw5Vu](https://user-images.githubusercontent.com/100245642/155273760-08e65003-51c2-49f4-a02c-91855ff33b28.png)

I'm not really sure how this happened. Talas keeps doing the check under sole animation while he is stuck.

**Comment by xavier150** [comment] 2022-03-22 03:51
@IttyBittyNiko 
Thanks for the report! 
You know how reproduce it ?

**Comment by xavier150** [comment] 2022-12-14 05:02
Hello, Thanks for the report! Since this issue was fixed so I will close it

**Closed by xavier150** 2022-12-14 05:02 UTC
Labels: R Major, T Animation Issue
